# Generated by Django 5.2.17 on 2026-09-26 22:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('venues', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrowdReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crowd_level', models.PositiveSmallIntegerField(choices=[(0, 'Empty'), (1, 'Light'), (2, 'Moderate'), (3, 'Busy'), (4, 'Crowded'), (5, 'Packed')])),
                ('wait_time', models.PositiveSmallIntegerField(choices=[(0, '0-5 minutes'), (1, '5-10 minutes'), (2, '10-20 minutes'), (3, '20-30 minutes'), (4, '30+ minutes'), (5, 'Not sure')])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crowd_reports', to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='crowd_reports', to='venues.venue')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['venue', '-created_at'], name='report_venue_time_idx'), models.Index(fields=['created_at'], name='report_created_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('crowd_level__in', [0, 1, 2, 3, 4, 5])), name='report_crowd_level_valid'), models.CheckConstraint(condition=models.Q(('wait_time__in', [0, 1, 2, 3, 4, 5])), name='report_wait_time_valid')],
            },
        ),
    ]
