# Generated by Django 5.2.17 on 2026-09-26 22:50

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(help_text='Two-letter USPS abbreviation, such as MD.', max_length=2)),
                ('latitude', models.DecimalField(decimal_places=6, help_text='Decimal degrees, between -90 and 90.', max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('-90')), django.core.validators.MaxValueValidator(Decimal('90'))])),
                ('longitude', models.DecimalField(decimal_places=6, help_text='Decimal degrees, between -180 and 180.', max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('-180')), django.core.validators.MaxValueValidator(Decimal('180'))])),
                ('description', models.TextField(blank=True)),
                ('cover_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cover charge in US dollars.', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['city', 'state'], name='venue_city_state_idx'), models.Index(fields=['latitude', 'longitude'], name='venue_coordinates_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('latitude__gte', -90), ('latitude__lte', 90)), name='venue_latitude_range'), models.CheckConstraint(condition=models.Q(('longitude__gte', -180), ('longitude__lte', 180)), name='venue_longitude_range'), models.CheckConstraint(condition=models.Q(('cover_fee__gte', 0)), name='venue_cover_fee_non_negative')],
            },
        ),
    ]
