// Hallmark · pre-emit critique: P5 H5 E4 S5 R5 V4
// Mobile discovery list · modern-minimal · custom neutral + forest accent
export const colors = {
  ink: "#202925",
  muted: "#66716C",
  subtle: "#8A948E",
  accent: "#24634B",
  accentLight: "#EDF5EF",
  white: "#FFFFFF",
  background: "#F7F9F7",
  border: "#E2E7E3",
  pressed: "#F0F3F0",
  quiet: "#24634B",
  quietBg: "#EDF5EF",
  moderate: "#657229",
  moderateBg: "#F2F4E6",
  busy: "#94600F",
  busyBg: "#FBF2DF",
  packed: "#A34738",
  packedBg: "#F9EDE9",
  scrim: "rgba(20,32,25,0.45)",
  photoScrim: "rgba(20,32,25,0.60)",
  focus: "#24634B",
  mapLand: "#F0F1EA",
  mapPark: "#DCE8D8",
  mapRoad: "#FFFFFF",
  mapWater: "#DDE9ED",
};
export const font = {
  regular: "Manrope_400Regular",
  medium: "Manrope_500Medium",
  semibold: "Manrope_600SemiBold",
  bold: "Manrope_700Bold",
  extra: "Manrope_800ExtraBold",
};
export const levels = [
  {
    name: "Quiet",
    detail: "Plenty of space. Easy to find a seat.",
    short: "Room to relax",
    color: colors.quiet,
    bg: colors.quietBg,
    backend: 1,
  },
  {
    name: "Moderate",
    detail: "A good buzz, with room to move.",
    short: "A little buzz",
    color: colors.moderate,
    bg: colors.moderateBg,
    backend: 2,
  },
  {
    name: "Busy",
    detail: "Most seats taken. Expect a crowd.",
    short: "Getting lively",
    color: colors.busy,
    bg: colors.busyBg,
    backend: 3,
  },
  {
    name: "Packed",
    detail: "Standing room. Hard to move around.",
    short: "Full house",
    color: colors.packed,
    bg: colors.packedBg,
    backend: 5,
  },
] as const;
